### PR TITLE
port to gcc 14

### LINKED ISSUE #184: Fails to compile on GCC 14
Looks like incompatible pointer types are now considered an error. [Fedora Wiki](https://fedoraproject.org/wiki/Changes/PortingToModernC#Use_of_incompatible_pointer_types_without_a_cast)

```make
make[1]: Leaving directory '/builddir/build/BUILD/JDSP4Linux-2.7.0/libjamesdsp'
subtree/Main/libjamesdsp/jni/jamesdsp/jdsp/Effects/crossfeed.c: In function â€˜CrossfeedEnableâ€™:
subtree/Main/libjamesdsp/jni/jamesdsp/jdsp/Effects/crossfeed.c:65:45: error: assignment to â€˜void (*)(struct dspsys *, size_t)â€™ {aka â€˜void (*)(struct dspsys *, long unsigned int)â€™} from incompatible pointer type â€˜void (*)(JamesDSPLib *, size_t)â€™ {aka â€˜void (*)(struct dspsys *, long unsigned int)â€™} [-Wincompatible-pointer-types]
   65 |                         jdsp->advXF.process = CrossfeedProcessFFTConvolver2x4x2;
      |                                             ^
subtree/Main/libjamesdsp/jni/jamesdsp/jdsp/Effects/crossfeed.c:73:45: error: assignment to â€˜void (*)(struct dspsys *, size_t)â€™ {aka â€˜void (*)(struct dspsys *, long unsigned int)â€™} from incompatible pointer type â€˜void (*)(JamesDSPLib *, size_t)â€™ {aka â€˜void (*)(struct dspsys *, long unsigned int)â€™} [-Wincompatible-pointer-types]
   73 |                         jdsp->advXF.process = CrossfeedProcessTwoStageFFTConvolver2x4x2;
      |                                             ^
subtree/Main/libjamesdsp/jni/jamesdsp/jdsp/Effects/crossfeed.c: In function â€˜CrossfeedProcessâ€™:
subtree/Main/libjamesdsp/jni/jamesdsp/jdsp/Effects/crossfeed.c:124:37: error: passing argument 1 of â€˜jdsp->advXF.processâ€™ from incompatible pointer type [-Wincompatible-pointer-types]
  124 |                 jdsp->advXF.process(jdsp, (unsigned int)n);
      |                                     ^~~~
      |                                     |
      |                                     JamesDSPLib * {aka struct dspsys *}
subtree/Main/libjamesdsp/jni/jamesdsp/jdsp/Effects/crossfeed.c:124:37: note: expected â€˜struct dspsys *â€™ but argument is of type â€˜JamesDSPLib *â€™ {aka â€˜struct dspsys *â€™}
make[1]: *** [Makefile:720: crossfeed.o] Error 1
```

### PR DESCRIPTION
**Pull request by theAeon**
fixes #184 for the subtree library, submodules still do not build. Unsure if JDSP4Linux frontend has further issues.

### CODE REVIEW

**Comment by theAeon** [comment]
Actually, I lied. Bear with.

**Comment by theAeon** [comment]
it builds now

File: libjamesdsp/JdspImpResToolbox.c [hunk 1]
```diff
@@ -252,10 +252,26 @@ static void decompressResamplerMQ(const double y[701], float *yi)
...
+{
+        k = k % n;
+        jds_reverse(arr, 0, n - 1);
+        jds_reverse(arr, 0, n - k - 1);
+        jds_reverse(arr, n - k, n - 1);
+}
 void circshift(float *x, int n, int k)
 {
-    k < 0 ? shift(x, -k, n) : shift(x, n - k, n);
+    k < 0 ? jds_shift(x, -k, n) : jds_shift(x, n - k, n);
```
Comment (theAeon) [inline libjamesdsp/JdspImpResToolbox.c:274]: this is messy but i'm bad at c and couldn't get it to stop having multiple-defined symbols w/o naming it differently
